"""rename_level_to_severity_and_update_alerts

Revision ID: f95af747fe93
Revises: e5d181f3724f
Create Date: 2026-01-13 12:33:14.563426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95af747fe93'
down_revision: Union[str, Sequence[str], None] = 'e5d181f3724f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_cache', 'updated_at')
    op.add_column('alerts', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('alerts', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('alerts', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('alerts', 'level')
    op.drop_index(op.f('uniq_mpesa_reference'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uniq_mpesa_reference'), 'transactions', ['user_id', 'reference'], unique=True)
    op.add_column('alerts', sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('alerts', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'severity')
    op.add_column('ai_cache', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
